version: '3.9'

services:
  postgres-1:
    environment:
      REPMGR_PARTNER_NODES: ${REPMGR_PARTNER_NODES}
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-1"

  postgres-2:
    image: bitnami/postgresql-repmgr:14
    environment:
      POSTGRESQL_PASSWORD: ${HF_POSTGRESQL_PASSWORD}
      POSTGRESQL_USERNAME: ${HF_POSTGRESQL_USERNAME}
      POSTGRESQL_DATABASE: ${HF_POSTGRESQL_DATABASE}
      REPMGR_NODE_NETWORK_NAME: postgres-2
      REPMGR_PASSWORD: ${REPMGR_PASSWORD}
      REPMGR_RECONNECT_INTERVAL: 3
      REPMGR_NODE_NAME: postgres-2
      REPMGR_PRIMARY_HOST: ${REPMGR_PRIMARY_HOST}
      REPMGR_PARTNER_NODES: ${REPMGR_PARTNER_NODES}
      POSTGRESQL_POSTGRES_PASSWORD: ${HAPI_POSTGRES_PASSWORD}
      REPMGR_FAILOVER: ${HF_POSTGRES_FAILOVER}
      REPMGR_DEGRADED_MONITORING_TIMEOUT: ${HF_POSTGRES_DEGRADED_MONITORING_TIMEOUT}
    volumes:
      - 'hapi-postgres-2-data:/bitnami/postgresql'
    configs:
      - target: /bitnami/postgresql/conf/conf.d/custom_postgresql.conf
        source: postgresql.conf
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-2"
      replicas: 1
      resources:
        limits:
          cpus: ${HF_POSTGRES_CPU_LIMIT}
          memory: ${HF_POSTGRES_MEMORY_LIMIT}
        reservations:
          cpus: ${HF_POSTGRES_CPU_RESERVE}
          memory: ${HF_POSTGRES_MEMORY_RESERVE}
    networks:
      default:
      pg_backup_net:

  postgres-3:
    image: bitnami/postgresql-repmgr:14
    environment:
      POSTGRESQL_PASSWORD: ${HF_POSTGRESQL_PASSWORD}
      POSTGRESQL_USERNAME: ${HF_POSTGRESQL_USERNAME}
      POSTGRESQL_DATABASE: ${HF_POSTGRESQL_DATABASE}
      REPMGR_NODE_NETWORK_NAME: postgres-3
      REPMGR_PASSWORD: ${REPMGR_PASSWORD}
      REPMGR_RECONNECT_INTERVAL: 3
      REPMGR_NODE_NAME: postgres-3
      REPMGR_PRIMARY_HOST: ${REPMGR_PRIMARY_HOST}
      REPMGR_PARTNER_NODES: ${REPMGR_PARTNER_NODES}
      POSTGRESQL_POSTGRES_PASSWORD: ${HAPI_POSTGRES_PASSWORD}
      REPMGR_FAILOVER: ${HF_POSTGRES_FAILOVER}
      REPMGR_DEGRADED_MONITORING_TIMEOUT: ${HF_POSTGRES_DEGRADED_MONITORING_TIMEOUT}
    volumes:
      - 'hapi-postgres-3-data:/bitnami/postgresql'
    configs:
      - target: /bitnami/postgresql/conf/conf.d/custom_postgresql.conf
        source: postgresql.conf
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-3"
      replicas: 1
      resources:
        limits:
          cpus: ${HF_POSTGRES_CPU_LIMIT}
          memory: ${HF_POSTGRES_MEMORY_LIMIT}
        reservations:
          cpus: ${HF_POSTGRES_CPU_RESERVE}
          memory: ${HF_POSTGRES_MEMORY_RESERVE}
    networks:
      default:
      pg_backup_net:

volumes:
  hapi-postgres-2-data:
  hapi-postgres-3-data:
